// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComStudtoolGoRestPkgRestTests(in *jlexer.Lexer, out *TestingJSONType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "some_field":
			out.SomeField = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComStudtoolGoRestPkgRestTests(out *jwriter.Writer, in TestingJSONType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"some_field\":"
		out.RawString(prefix[1:])
		out.String(string(in.SomeField))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TestingJSONType) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComStudtoolGoRestPkgRestTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TestingJSONType) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComStudtoolGoRestPkgRestTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TestingJSONType) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComStudtoolGoRestPkgRestTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TestingJSONType) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComStudtoolGoRestPkgRestTests(l, v)
}
